EMPTY_SPACE = "."
STARTING = "STARTING"
EXIT = "EXIT"
EASY_PATH = "EASY_PATH"

UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"
MIDDLE = "MIDDLE"


OPPOSITE_FACES = {UP: DOWN, DOWN: UP, LEFT: RIGHT, RIGHT: LEFT}


ROOM_KINDS = {STARTING: "S", EXIT: "E", EASY_PATH: "P"}
