EMPTY_SPACE = "."
STARTING = "STARTING"
EXIT = "EXIT"

UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"
MIDDLE = "MIDDLE"

OPPOSITE_FACES = {UP: DOWN, DOWN: UP, LEFT: RIGHT, RIGHT: LEFT}


ROOM_KINDS = {STARTING: "S", EXIT: "E"}
